import type { FoodEntry } from './types'

// Priority convention:
//   0  = Personal / branded library (always preferred)
//   10 = Generic canonical entries (USDA-style fallbacks)

/**
 * PERSONAL FOOD LIBRARY — branded, high-priority entries.
 * These always win over generic foods when an alias matches.
 */
export const PERSONAL_FOODS: FoodEntry[] = [
  {
    id: 'slate',
    name: 'Slate Protein Shake',
    aliases: ['slate', 'slate shake', 'slate protein shake', 'slate chocolate'],
    unit: 'bottle',
    servingLabel: '1 bottle (15 fl oz)',
    calories: 180,
    protein: 42,
    carbs: 2,
    fat: 1,
    fiber: 1,
    priority: 0,
    defaultAmount: 1, // "Slate" => 1 bottle
    notes: 'Elite protein efficiency (23.3g / 100 kcal).',
  },
  {
    id: 'whey',
    name: 'Whey Protein Powder',
    aliases: ['whey', 'whey isolate', 'whey protein', 'protein shake', 'protein powder'],
    unit: 'scoop',
    servingLabel: '1 scoop',
    calories: 120,
    protein: 25,
    carbs: 3,
    fat: 1,
    priority: 0,
    defaultAmount: 1,
    notes: 'Assume mixed with water unless stated otherwise.',
  },
  {
    id: 'chobani',
    name: 'Chobani Greek Yogurt (Plain, 20g)',
    aliases: ['greek yogurt', 'chobani', 'chobani 20g', 'chobani greek yogurt', 'yogurt'],
    unit: 'serving',
    servingLabel: '3/4 cup (190g)',
    calories: 140,
    protein: 20,
    carbs: 8,
    fat: 3,
    priority: 0,
    defaultAmount: 1, // "greek yogurt" = 1 serving
    portionRules: {
      cup: 1.33, // 1 cup = 1.33 servings
      tub: 5, // whole tub = 5 servings
    },
    notes: 'Strong PSMF staple.',
  },
  {
    id: 'good-culture-cc',
    name: 'Good Culture Cottage Cheese',
    aliases: ['cottage cheese', 'good culture'],
    unit: 'serving',
    servingLabel: '1/2 cup (110g)',
    calories: 90,
    protein: 14,
    carbs: 4,
    fat: 2,
    priority: 0,
    defaultAmount: 2, // "cottage cheese" = 1 cup default (2 servings)
    portionRules: {
      cup: 2, // 1 cup = 2 servings
      tub: 4, // whole tub = 4 servings
    },
    notes: 'Strong PSMF. Default portion is 1 cup (2 servings).',
  },
  {
    id: 'chicken-breast',
    name: 'Chicken Breast (cooked, skinless)',
    aliases: [
      'chicken breast',
      'grilled chicken',
      'baked chicken',
      'shredded chicken',
      'chicken',
    ],
    unit: 'oz',
    servingLabel: '1 oz cooked',
    calories: 47,
    protein: 8.8,
    carbs: 0,
    fat: 1,
    priority: 0,
    perOunce: true,
    meat: true,
    defaultAmount: 6, // bare "chicken" => 6 oz
    notes: 'Canonical meat. Weights assumed COOKED.',
  },
]

/**
 * GENERIC CANONICAL FOODS — USDA-style fallbacks.
 * Meats are per-ounce (cooked). Others are per their natural serving.
 */
export const GENERIC_FOODS: FoodEntry[] = [
  // ---- Meats / proteins (per oz cooked) ----
  {
    id: 'sirloin',
    name: 'Sirloin Steak (cooked)',
    aliases: ['sirloin', 'steak', 'top sirloin'],
    unit: 'oz',
    servingLabel: '1 oz cooked',
    calories: 57,
    protein: 8.7,
    carbs: 0,
    fat: 2.3,
    priority: 10,
    perOunce: true,
    meat: true,
    defaultAmount: 8,
  },
  {
    id: 'lean-beef',
    name: '93% Lean Ground Beef (cooked)',
    aliases: ['lean beef', '93% lean beef', 'ground beef', '93/7 beef', 'hamburger'],
    unit: 'oz',
    servingLabel: '1 oz cooked',
    calories: 50,
    protein: 7.5,
    carbs: 0,
    fat: 2.2,
    priority: 10,
    perOunce: true,
    meat: true,
    defaultAmount: 6,
  },
  {
    id: 'tuna',
    name: 'Tuna (canned in water)',
    aliases: ['tuna', 'canned tuna', 'tuna fish'],
    unit: 'oz',
    servingLabel: '1 oz drained',
    calories: 33,
    protein: 7.3,
    carbs: 0,
    fat: 0.3,
    priority: 10,
    perOunce: true,
    meat: true,
    defaultAmount: 5,
  },
  {
    id: 'salmon',
    name: 'Salmon (cooked)',
    aliases: ['salmon', 'grilled salmon', 'baked salmon'],
    unit: 'oz',
    servingLabel: '1 oz cooked',
    calories: 58,
    protein: 7.2,
    carbs: 0,
    fat: 3.3,
    priority: 10,
    perOunce: true,
    meat: true,
    defaultAmount: 6,
  },
  {
    id: 'cod',
    name: 'Cod (cooked)',
    aliases: ['cod', 'white fish', 'whitefish'],
    unit: 'oz',
    servingLabel: '1 oz cooked',
    calories: 30,
    protein: 6.5,
    carbs: 0,
    fat: 0.3,
    priority: 10,
    perOunce: true,
    meat: true,
    defaultAmount: 6,
  },
  {
    id: 'shrimp',
    name: 'Shrimp (cooked)',
    aliases: ['shrimp', 'prawns'],
    unit: 'oz',
    servingLabel: '1 oz cooked',
    calories: 28,
    protein: 6,
    carbs: 0.2,
    fat: 0.3,
    priority: 10,
    perOunce: true,
    meat: true,
    defaultAmount: 5,
  },
  // ---- Eggs ----
  {
    id: 'egg-whites',
    name: 'Egg Whites',
    aliases: ['egg whites', 'egg white', 'liquid egg whites'],
    unit: 'white',
    servingLabel: '1 white',
    calories: 16,
    protein: 3.3,
    carbs: 0.2,
    fat: 0,
    priority: 10,
    defaultAmount: 4, // bare "egg whites" => 4 whites
    portionRules: { cup: 8 }, // 1 cup ~ 8 whites
  },
  {
    id: 'whole-eggs',
    name: 'Whole Eggs',
    aliases: ['whole eggs', 'whole egg', 'eggs', 'egg'],
    unit: 'egg',
    servingLabel: '1 large egg',
    calories: 72,
    protein: 6.3,
    carbs: 0.4,
    fat: 5,
    priority: 10,
    defaultAmount: 2,
  },
  // ---- Vegetables / fruit ----
  {
    id: 'berries',
    name: 'Mixed Berries',
    aliases: ['berries', 'blueberries', 'strawberries', 'raspberries', 'mixed berries'],
    unit: 'cup',
    servingLabel: '1 cup',
    calories: 60,
    protein: 1,
    carbs: 14,
    fat: 0.5,
    fiber: 4,
    priority: 10,
    defaultAmount: 1,
  },
  {
    id: 'asparagus',
    name: 'Asparagus',
    aliases: ['asparagus'],
    unit: 'cup',
    servingLabel: '1 cup',
    calories: 27,
    protein: 3,
    carbs: 5,
    fat: 0,
    fiber: 3,
    priority: 10,
    defaultAmount: 1,
  },
  {
    id: 'broccoli',
    name: 'Broccoli',
    aliases: ['broccoli'],
    unit: 'cup',
    servingLabel: '1 cup',
    calories: 31,
    protein: 2.5,
    carbs: 6,
    fat: 0,
    fiber: 2.4,
    priority: 10,
    defaultAmount: 1,
  },
  {
    id: 'salad-greens',
    name: 'Salad Greens',
    aliases: ['salad greens', 'salad', 'mixed greens', 'lettuce', 'spinach', 'arugula'],
    unit: 'cup',
    servingLabel: '1 cup',
    calories: 8,
    protein: 0.7,
    carbs: 1.5,
    fat: 0,
    fiber: 1,
    priority: 10,
    defaultAmount: 2,
  },
  // ---- Fats / oils / dressings ----
  {
    id: 'olive-oil',
    name: 'Olive Oil',
    aliases: ['olive oil', 'evoo', 'oil'],
    unit: 'tbsp',
    servingLabel: '1 tbsp',
    calories: 120,
    protein: 0,
    carbs: 0,
    fat: 14,
    priority: 10,
    defaultAmount: 1,
    portionRules: { tsp: 0.333 },
  },
  {
    id: 'butter',
    name: 'Butter',
    aliases: ['butter'],
    unit: 'tbsp',
    servingLabel: '1 tbsp',
    calories: 100,
    protein: 0,
    carbs: 0,
    fat: 11,
    priority: 10,
    defaultAmount: 1,
    portionRules: { tsp: 0.333, pat: 0.36 },
  },
  {
    id: 'dressing',
    name: 'Salad Dressing',
    aliases: ['dressing', 'ranch', 'vinaigrette', 'caesar dressing'],
    unit: 'tbsp',
    servingLabel: '1 tbsp',
    calories: 73,
    protein: 0.2,
    carbs: 1.5,
    fat: 7.5,
    priority: 10,
    defaultAmount: 2,
  },
]

export const BASE_FOODS: FoodEntry[] = [...PERSONAL_FOODS, ...GENERIC_FOODS]

/** Merge built-in foods with the user's custom foods. Custom foods get top priority. */
export function getFoodDatabase(customFoods: FoodEntry[] = []): FoodEntry[] {
  const custom = customFoods.map((f) => ({ ...f, priority: -1, custom: true }))
  return [...custom, ...BASE_FOODS]
}
