const EFFECTIVE = 'August 22, 2026';
const CONTACT = 'privacy@petguardian.app';

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-2">
      <h2 className="text-lg font-bold text-brand-900">{title}</h2>
      <div className="text-sm text-slate-700 space-y-2 leading-relaxed">{children}</div>
    </section>
  );
}

export default function PrivacyPage() {
  return (
    <div className="max-w-2xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-brand-900">Privacy Policy</h1>
        <p className="text-sm text-slate-500">Effective {EFFECTIVE}</p>
      </div>

      <p className="text-sm text-slate-700 leading-relaxed">
        PetGuardian (“we,” “us”) helps pet owners create a funded, state-specific care plan for their animals.
        This policy explains what we collect, how we use it, and the choices you have. PetGuardian is a
        self-help planning tool, not a law firm, and does not provide legal advice.
      </p>

      <Section title="Information we collect">
        <p>We collect only what you provide to create your plan:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li><strong>Account:</strong> your name, email, password (stored only as a secure hash), role, and state.</li>
          <li><strong>Plan content:</strong> details about your pets, chosen caregivers and trustees (their names and contact details, which you provide), funding sources and amounts, and your care and disposition instructions.</li>
          <li><strong>Technical:</strong> basic server logs needed to operate and secure the service.</li>
        </ul>
        <p>We do not knowingly collect information from children under 13, and the service is intended for adults.</p>
      </Section>

      <Section title="How we use your information">
        <p>We use your information solely to provide the service: to save your plan, generate your documents (the trust directive, care memorandum, and emergency card), and let you return to and update your plan. We do not use your plan content for advertising.</p>
      </Section>

      <Section title="How your information is stored and protected">
        <p>Your data is stored in a secured database and transmitted over encrypted connections (HTTPS/TLS). Access is protected by authentication. No method of storage or transmission is perfectly secure, but we take reasonable measures to protect your information.</p>
      </Section>

      <Section title="Sharing, referrals, and affiliates">
        <p>We do not sell your personal information. If we offer optional referrals to third parties (for example pet insurance or attorney review), those are shown only with your action and we clearly disclose any relationship where we may earn a fee. We share your details with a third party only when you choose to proceed.</p>
      </Section>

      <Section title="Deleting your account and data">
        <p>You can permanently delete your account at any time from <strong>Account → Delete account</strong> inside the app. Deleting your account immediately and permanently removes your profile and all associated plans, pets, caregivers, trustees, and funding records. This cannot be undone.</p>
        <p>You may also contact us at {CONTACT} to request deletion or a copy of your data.</p>
      </Section>

      <Section title="Your rights">
        <p>Depending on where you live, you may have rights to access, correct, delete, or restrict use of your personal information, and to opt out of any sale or sharing. We honor a “Do Not Sell or Share My Personal Information” request; because we do not sell personal information, this is our default posture. To exercise any right, contact {CONTACT}.</p>
      </Section>

      <Section title="Changes to this policy">
        <p>We may update this policy. Material changes will be reflected by a new effective date at the top of this page.</p>
      </Section>

      <Section title="Contact">
        <p>Questions about this policy or your data: {CONTACT}.</p>
      </Section>

      <p className="text-xs text-slate-400 pt-4 border-t border-slate-200">
        This document is provided for transparency about data handling and is not legal advice. Document
        templates generated by PetGuardian are drafts intended for review with a licensed attorney in your
        state before signing or funding.
      </p>
    </div>
  );
}
